### ISSUE TITLE
Code generates no data in output folder

### ISSUE THREAD

**Issue by xXComanderXx** [bkelly-lab/ReplicationCrisis#2]
Thank you for sharing your project.
I encountered some issues running your code on SAS Studio (3.81 Basic Edition). After running the code the output folder contains only empty zip files. I would appreciate your help. Thanks in advance.

I will share LOGs if the current run is completed because I didn't save the LOGs from the last run

**Comment by xXComanderXx** [comment]
[LOG.txt](https://github.com/bkelly-lab/ReplicationCrisis/files/8707456/LOG.txt)
Hey,
Now i have the LOG file. The ERROR occurs because I don't have appropriate authorization level for file CRSP.MCTI.DATA. How can I get the authorization level. Do I have to tell my university the specific file I want to access or are there general access levels in WRDS or maybe you can 
authorize me? Thank you so much in advance.

**Comment by theisij** [comment]
Hi, 
Thanks for attaching your log file. I agree that the issue seems to be that your university doesn't subscribe to the CRSP.MSCI table. However, I find that a bit strange since it seems like you have access to the CRSP.MSF. I would reach out to the WRDS support staff and ask what's going on. Unfortunately, we can't authorize your access.

**Comment by boixalice** [comment]
Hi, 
First of all thank you for sharing your project. 
Unfortunately, I encounter the same issue while trying to generate the data. Do you have any update on this topic ? 
Regards,

**Comment by theisij** [comment]
If your issue is also with the CRSP.MSCI table, there's unfortunately not much we can do. I would try to reach out to the WRDS support staff. If the issue is an empty zip folder, but with an unknown cause, try to attach your log file and I'll see what I can do.

**Comment by xXComanderXx** [comment]
Sorry for the late reply. My university does not subscribe to the CRSP.MSCI table but in my case it was possible to change the code to tables my university subscribes. My suggestion is to search in the code where CRSP.MSCI table is used and maybe you do not need this part, then you can comment it out or you can try to get this data from another table. 
Best regards
