### ISSUE TITLE
Mispricing Score Interpretation

### ISSUE THREAD

**Issue by sehoff** [bkelly-lab/ReplicationCrisis#3]
Hi, 

I am wondering about the ranking of the mispricing scores. In the [documentation](https://finance.wharton.upenn.edu/~stambaug/Mispricing_Measure_Documentation.pdf) of Stambaugh, Yu, Yuan, their mispricing score has the following interpretation: 

 _According to this measure, the stocks with the highest values of MISP are the most “overpriced,” and those with the lowest values are the most “underpriced.”_

As I am a novice to SAS programming I cannot answer the following question by looking at the source code: Is the mispricing measure you provide sorted in the same way, i.e., should stocks with a high mispricing measure have **lower** next month returns ? From what I understand, you sign the variables according to the findings in the literature, and the sort descending, which would yield the opposite interpretation, i.e., a high mispricing measure is associated with higher (not lower) next month returns. 

Thanks for a clarification and best regards!

**Comment by theisij** [comment]
Actually, our mispricing_mgmt and mispricing_perf characteristic are sorted such that a high (e.g.) mispricing_mgmt is associated with returns next month. 

Table 8 in our documentation (https://www.dropbox.com/sh/61j1v0sieq9z210/AACdJ68fs5_eT_eJMunwMBWia?dl=0), shows the sign/direction of each factor. If sign=1, a high factor characteristic forecasts high returns, while sign=-1 implies that a high factor characteristic forecasts low returns.

**Comment by sehoff** [comment]
Ok, thanks a lot for the clarification and the quick reply.
