### ISSUE TITLE
Code can't generate the output

### ISSUE THREAD

**Issue by mingjun-sun** [bkelly-lab/ReplicationCrisis#4]
After running the code the output folder contains only the following files. 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/50226927/235006124-61010e02-385e-43b0-8bc6-a375d1fabb29.png">

The log file is attached.
[main.log](https://github.com/bkelly-lab/ReplicationCrisis/files/11348456/main.log)

**Comment by theisij** [comment]
There's nothing out of the ordinary in the log file, except that the code doesn't seem to have finished. From the log file, I can see that you have the correct permissions for the data, so write me an email at tij.fi@cbs.dk, and I'll send you the data.
