### ISSUE TITLE
How to Retrieve Firm-Level Variable Data from WRDS?

### ISSUE THREAD

**Issue by jaepil-choi** [bkelly-lab/ReplicationCrisis#8]
I would like to express my sincere gratitude to @mk0417 and @theisij for their invaluable assistance in issue #6. Your guidance in correcting my SAS code save directory and providing the URL to the main output on WRDS has been instrumental in advancing my research. Thank you very much for your help.

Upon further investigation, I realized that the WRDS data includes returns and characteristics data, but it does not contain the firm-level variable data used to construct each characteristic, as I had initially assumed.

Could you please advise on how to obtain the missing firm-level variable data? I understand that the original SAS code must have accessed firm-level variable data to generate the characteristics data. If this firm-level data is not directly available, I would greatly appreciate any guidance on how to modify the SAS code to retrieve it with minimal changes.

Thank you once again for your continued support and assistance. Your expertise is greatly appreciated.

**Comment by theisij** [comment]
The firm-level characteristics are generated on line 91-94 in the GlobalFactors/main.sas file, so I suggest adding a "save to csv" command immediately after.

**Comment by jaepil-choi** [comment]
Tried to dump the data right after the table generation but it always resulted in the empty 128kb file. Seems like missing CCM data is stopping the table creation from the very beginning. Just requested my school to subscribe to the CCM dataset to run Replication Crisis. Thanks for the kind follow up though!
